// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleList: typeof import('./src/components/ArticleList/index.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop/index.vue')['default']
    Comment: typeof import('./src/components/Comment/index.vue')['default']
    Copyright: typeof import('./src/components/Copyright/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    MdToHtml: typeof import('./src/components/MdToHtml/index.vue')['default']
    MyContainer: typeof import('./src/components/MyContainer/index.vue')['default']
    Nav: typeof import('./src/components/Nav/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    TopProgress: typeof import('./src/components/TopProgress/index.vue')['default']
  }
}

export { }
